apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudops-ai

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloudops-ai

  template:

    metadata:
      labels:
        app: cloudops-ai

    spec:

      containers:
        - name: cloudops-ai

          image: cloudops-ai:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000