apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: router-agent

  template:
    metadata:
      labels:
        app: router-agent

    spec:
      containers:
      - name: router-agent
        image: router-agent:latest

        ports:
        - containerPort: 8000